# 配置服务注册中心
#    server.port=8081
#    eureka.environment=work
#  # 设置是否将自己作为客户端注册到注册中心（缺省true）
#  # 这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
#    eureka.client.register-with-eureka=false

#  # 设置是否从注册中心获取注册信息（缺省true）
#  # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
#    eureka.client.fetch-registry=false
#    eureka.client.serviceUrl.defaultZone=http://localhost:${server.port}/eureka/
#  #是否开启自我保护模式，默认为true。
#    eureka.server.enable-self-preservation=true
#  #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
#    eureka.server.eviction-interval-timer-in-ms=10000




server:
    port: 8761  #服务的端口号
eureka:
    instance:
        hostname: eureka-server #eureka的实例名
    client:
        register-with-eureka: false  #设置是否将自己作为客户端注册到注册中心（缺省true）
        fetch-registry: false  #设置是否从注册中心获取注册信息（缺省true）
        service-url:
            defaultZone: http://localhost:${server.port}/eureka/